export const testIds = {
  errorState: 'error-state',
  errorRetryButton: 'error-state-retry',
  eventCard: (id: number | string) => `event-card-${id}`,
  coachCard: (id: number | string) => `coach-card-${id}`,
  groupCard: (id: number | string) => `group-card-${id}`,
  groupsScreen: 'groups-screen',
  groupsExploreTab: 'groups-tab-explore',
  groupsSearchTab: 'groups-tab-search',
  groupsStatesTab: 'groups-tab-states',
  groupsSearchFilterButton: 'groups-search-filter-button',
  groupsSearchModal: 'groups-search-modal',
  groupsSearchInput: 'groups-search-input',
  groupsSearchApplyButton: 'groups-search-apply-button',
  groupsSearchStateButton: 'groups-search-state-button',
  groupsStateModalCloseButton: 'groups-search-state-modal-close',
  groupsSearchClearFiltersButton: 'groups-search-clear-filters-button',
  groupsClearFiltersButton: 'groups-clear-filters-button',
  groupStateOption: (stateCode: string) => `group-state-option-${stateCode.toLowerCase()}`,
  groupStateCard: (stateCode: string) => `group-state-card-${stateCode.toLowerCase()}`,
} as const;
